// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/txrps/next-golang-project/model"
)

func newTmMasterDataType(db *gorm.DB, opts ...gen.DOOption) tmMasterDataType {
	_tmMasterDataType := tmMasterDataType{}

	_tmMasterDataType.tmMasterDataTypeDo.UseDB(db, opts...)
	_tmMasterDataType.tmMasterDataTypeDo.UseModel(&model.TmMasterDataType{})

	tableName := _tmMasterDataType.tmMasterDataTypeDo.TableName()
	_tmMasterDataType.ALL = field.NewAsterisk(tableName)
	_tmMasterDataType.MasterDataTypeID = field.NewInt32(tableName, "master_data_type_id")
	_tmMasterDataType.MasterDataTypeName = field.NewString(tableName, "master_data_type_name")

	_tmMasterDataType.fillFieldMap()

	return _tmMasterDataType
}

type tmMasterDataType struct {
	tmMasterDataTypeDo

	ALL                field.Asterisk
	MasterDataTypeID   field.Int32
	MasterDataTypeName field.String

	fieldMap map[string]field.Expr
}

func (t tmMasterDataType) Table(newTableName string) *tmMasterDataType {
	t.tmMasterDataTypeDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tmMasterDataType) As(alias string) *tmMasterDataType {
	t.tmMasterDataTypeDo.DO = *(t.tmMasterDataTypeDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tmMasterDataType) updateTableName(table string) *tmMasterDataType {
	t.ALL = field.NewAsterisk(table)
	t.MasterDataTypeID = field.NewInt32(table, "master_data_type_id")
	t.MasterDataTypeName = field.NewString(table, "master_data_type_name")

	t.fillFieldMap()

	return t
}

func (t *tmMasterDataType) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tmMasterDataType) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 2)
	t.fieldMap["master_data_type_id"] = t.MasterDataTypeID
	t.fieldMap["master_data_type_name"] = t.MasterDataTypeName
}

func (t tmMasterDataType) clone(db *gorm.DB) tmMasterDataType {
	t.tmMasterDataTypeDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tmMasterDataType) replaceDB(db *gorm.DB) tmMasterDataType {
	t.tmMasterDataTypeDo.ReplaceDB(db)
	return t
}

type tmMasterDataTypeDo struct{ gen.DO }

func (t tmMasterDataTypeDo) Debug() *tmMasterDataTypeDo {
	return t.withDO(t.DO.Debug())
}

func (t tmMasterDataTypeDo) WithContext(ctx context.Context) *tmMasterDataTypeDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tmMasterDataTypeDo) ReadDB() *tmMasterDataTypeDo {
	return t.Clauses(dbresolver.Read)
}

func (t tmMasterDataTypeDo) WriteDB() *tmMasterDataTypeDo {
	return t.Clauses(dbresolver.Write)
}

func (t tmMasterDataTypeDo) Session(config *gorm.Session) *tmMasterDataTypeDo {
	return t.withDO(t.DO.Session(config))
}

func (t tmMasterDataTypeDo) Clauses(conds ...clause.Expression) *tmMasterDataTypeDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tmMasterDataTypeDo) Returning(value interface{}, columns ...string) *tmMasterDataTypeDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tmMasterDataTypeDo) Not(conds ...gen.Condition) *tmMasterDataTypeDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tmMasterDataTypeDo) Or(conds ...gen.Condition) *tmMasterDataTypeDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tmMasterDataTypeDo) Select(conds ...field.Expr) *tmMasterDataTypeDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tmMasterDataTypeDo) Where(conds ...gen.Condition) *tmMasterDataTypeDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tmMasterDataTypeDo) Order(conds ...field.Expr) *tmMasterDataTypeDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tmMasterDataTypeDo) Distinct(cols ...field.Expr) *tmMasterDataTypeDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tmMasterDataTypeDo) Omit(cols ...field.Expr) *tmMasterDataTypeDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tmMasterDataTypeDo) Join(table schema.Tabler, on ...field.Expr) *tmMasterDataTypeDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tmMasterDataTypeDo) LeftJoin(table schema.Tabler, on ...field.Expr) *tmMasterDataTypeDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tmMasterDataTypeDo) RightJoin(table schema.Tabler, on ...field.Expr) *tmMasterDataTypeDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tmMasterDataTypeDo) Group(cols ...field.Expr) *tmMasterDataTypeDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tmMasterDataTypeDo) Having(conds ...gen.Condition) *tmMasterDataTypeDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tmMasterDataTypeDo) Limit(limit int) *tmMasterDataTypeDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tmMasterDataTypeDo) Offset(offset int) *tmMasterDataTypeDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tmMasterDataTypeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *tmMasterDataTypeDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tmMasterDataTypeDo) Unscoped() *tmMasterDataTypeDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tmMasterDataTypeDo) Create(values ...*model.TmMasterDataType) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tmMasterDataTypeDo) CreateInBatches(values []*model.TmMasterDataType, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tmMasterDataTypeDo) Save(values ...*model.TmMasterDataType) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tmMasterDataTypeDo) First() (*model.TmMasterDataType, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TmMasterDataType), nil
	}
}

func (t tmMasterDataTypeDo) Take() (*model.TmMasterDataType, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TmMasterDataType), nil
	}
}

func (t tmMasterDataTypeDo) Last() (*model.TmMasterDataType, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TmMasterDataType), nil
	}
}

func (t tmMasterDataTypeDo) Find() ([]*model.TmMasterDataType, error) {
	result, err := t.DO.Find()
	return result.([]*model.TmMasterDataType), err
}

func (t tmMasterDataTypeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TmMasterDataType, err error) {
	buf := make([]*model.TmMasterDataType, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tmMasterDataTypeDo) FindInBatches(result *[]*model.TmMasterDataType, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tmMasterDataTypeDo) Attrs(attrs ...field.AssignExpr) *tmMasterDataTypeDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tmMasterDataTypeDo) Assign(attrs ...field.AssignExpr) *tmMasterDataTypeDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tmMasterDataTypeDo) Joins(fields ...field.RelationField) *tmMasterDataTypeDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tmMasterDataTypeDo) Preload(fields ...field.RelationField) *tmMasterDataTypeDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tmMasterDataTypeDo) FirstOrInit() (*model.TmMasterDataType, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TmMasterDataType), nil
	}
}

func (t tmMasterDataTypeDo) FirstOrCreate() (*model.TmMasterDataType, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TmMasterDataType), nil
	}
}

func (t tmMasterDataTypeDo) FindByPage(offset int, limit int) (result []*model.TmMasterDataType, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tmMasterDataTypeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tmMasterDataTypeDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tmMasterDataTypeDo) Delete(models ...*model.TmMasterDataType) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tmMasterDataTypeDo) withDO(do gen.Dao) *tmMasterDataTypeDo {
	t.DO = *do.(*gen.DO)
	return t
}
