// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/txrps/next-golang-project/model"
)

func newTmRoleMappingPermission(db *gorm.DB, opts ...gen.DOOption) tmRoleMappingPermission {
	_tmRoleMappingPermission := tmRoleMappingPermission{}

	_tmRoleMappingPermission.tmRoleMappingPermissionDo.UseDB(db, opts...)
	_tmRoleMappingPermission.tmRoleMappingPermissionDo.UseModel(&model.TmRoleMappingPermission{})

	tableName := _tmRoleMappingPermission.tmRoleMappingPermissionDo.TableName()
	_tmRoleMappingPermission.ALL = field.NewAsterisk(tableName)
	_tmRoleMappingPermission.RoleID = field.NewInt32(tableName, "role_id")
	_tmRoleMappingPermission.MenuID = field.NewInt32(tableName, "menu_id")
	_tmRoleMappingPermission.Permission = field.NewInt32(tableName, "permission")

	_tmRoleMappingPermission.fillFieldMap()

	return _tmRoleMappingPermission
}

type tmRoleMappingPermission struct {
	tmRoleMappingPermissionDo

	ALL        field.Asterisk
	RoleID     field.Int32
	MenuID     field.Int32
	Permission field.Int32

	fieldMap map[string]field.Expr
}

func (t tmRoleMappingPermission) Table(newTableName string) *tmRoleMappingPermission {
	t.tmRoleMappingPermissionDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tmRoleMappingPermission) As(alias string) *tmRoleMappingPermission {
	t.tmRoleMappingPermissionDo.DO = *(t.tmRoleMappingPermissionDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tmRoleMappingPermission) updateTableName(table string) *tmRoleMappingPermission {
	t.ALL = field.NewAsterisk(table)
	t.RoleID = field.NewInt32(table, "role_id")
	t.MenuID = field.NewInt32(table, "menu_id")
	t.Permission = field.NewInt32(table, "permission")

	t.fillFieldMap()

	return t
}

func (t *tmRoleMappingPermission) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tmRoleMappingPermission) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 3)
	t.fieldMap["role_id"] = t.RoleID
	t.fieldMap["menu_id"] = t.MenuID
	t.fieldMap["permission"] = t.Permission
}

func (t tmRoleMappingPermission) clone(db *gorm.DB) tmRoleMappingPermission {
	t.tmRoleMappingPermissionDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tmRoleMappingPermission) replaceDB(db *gorm.DB) tmRoleMappingPermission {
	t.tmRoleMappingPermissionDo.ReplaceDB(db)
	return t
}

type tmRoleMappingPermissionDo struct{ gen.DO }

func (t tmRoleMappingPermissionDo) Debug() *tmRoleMappingPermissionDo {
	return t.withDO(t.DO.Debug())
}

func (t tmRoleMappingPermissionDo) WithContext(ctx context.Context) *tmRoleMappingPermissionDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tmRoleMappingPermissionDo) ReadDB() *tmRoleMappingPermissionDo {
	return t.Clauses(dbresolver.Read)
}

func (t tmRoleMappingPermissionDo) WriteDB() *tmRoleMappingPermissionDo {
	return t.Clauses(dbresolver.Write)
}

func (t tmRoleMappingPermissionDo) Session(config *gorm.Session) *tmRoleMappingPermissionDo {
	return t.withDO(t.DO.Session(config))
}

func (t tmRoleMappingPermissionDo) Clauses(conds ...clause.Expression) *tmRoleMappingPermissionDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tmRoleMappingPermissionDo) Returning(value interface{}, columns ...string) *tmRoleMappingPermissionDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tmRoleMappingPermissionDo) Not(conds ...gen.Condition) *tmRoleMappingPermissionDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tmRoleMappingPermissionDo) Or(conds ...gen.Condition) *tmRoleMappingPermissionDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tmRoleMappingPermissionDo) Select(conds ...field.Expr) *tmRoleMappingPermissionDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tmRoleMappingPermissionDo) Where(conds ...gen.Condition) *tmRoleMappingPermissionDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tmRoleMappingPermissionDo) Order(conds ...field.Expr) *tmRoleMappingPermissionDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tmRoleMappingPermissionDo) Distinct(cols ...field.Expr) *tmRoleMappingPermissionDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tmRoleMappingPermissionDo) Omit(cols ...field.Expr) *tmRoleMappingPermissionDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tmRoleMappingPermissionDo) Join(table schema.Tabler, on ...field.Expr) *tmRoleMappingPermissionDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tmRoleMappingPermissionDo) LeftJoin(table schema.Tabler, on ...field.Expr) *tmRoleMappingPermissionDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tmRoleMappingPermissionDo) RightJoin(table schema.Tabler, on ...field.Expr) *tmRoleMappingPermissionDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tmRoleMappingPermissionDo) Group(cols ...field.Expr) *tmRoleMappingPermissionDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tmRoleMappingPermissionDo) Having(conds ...gen.Condition) *tmRoleMappingPermissionDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tmRoleMappingPermissionDo) Limit(limit int) *tmRoleMappingPermissionDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tmRoleMappingPermissionDo) Offset(offset int) *tmRoleMappingPermissionDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tmRoleMappingPermissionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *tmRoleMappingPermissionDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tmRoleMappingPermissionDo) Unscoped() *tmRoleMappingPermissionDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tmRoleMappingPermissionDo) Create(values ...*model.TmRoleMappingPermission) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tmRoleMappingPermissionDo) CreateInBatches(values []*model.TmRoleMappingPermission, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tmRoleMappingPermissionDo) Save(values ...*model.TmRoleMappingPermission) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tmRoleMappingPermissionDo) First() (*model.TmRoleMappingPermission, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TmRoleMappingPermission), nil
	}
}

func (t tmRoleMappingPermissionDo) Take() (*model.TmRoleMappingPermission, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TmRoleMappingPermission), nil
	}
}

func (t tmRoleMappingPermissionDo) Last() (*model.TmRoleMappingPermission, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TmRoleMappingPermission), nil
	}
}

func (t tmRoleMappingPermissionDo) Find() ([]*model.TmRoleMappingPermission, error) {
	result, err := t.DO.Find()
	return result.([]*model.TmRoleMappingPermission), err
}

func (t tmRoleMappingPermissionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TmRoleMappingPermission, err error) {
	buf := make([]*model.TmRoleMappingPermission, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tmRoleMappingPermissionDo) FindInBatches(result *[]*model.TmRoleMappingPermission, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tmRoleMappingPermissionDo) Attrs(attrs ...field.AssignExpr) *tmRoleMappingPermissionDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tmRoleMappingPermissionDo) Assign(attrs ...field.AssignExpr) *tmRoleMappingPermissionDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tmRoleMappingPermissionDo) Joins(fields ...field.RelationField) *tmRoleMappingPermissionDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tmRoleMappingPermissionDo) Preload(fields ...field.RelationField) *tmRoleMappingPermissionDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tmRoleMappingPermissionDo) FirstOrInit() (*model.TmRoleMappingPermission, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TmRoleMappingPermission), nil
	}
}

func (t tmRoleMappingPermissionDo) FirstOrCreate() (*model.TmRoleMappingPermission, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TmRoleMappingPermission), nil
	}
}

func (t tmRoleMappingPermissionDo) FindByPage(offset int, limit int) (result []*model.TmRoleMappingPermission, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tmRoleMappingPermissionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tmRoleMappingPermissionDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tmRoleMappingPermissionDo) Delete(models ...*model.TmRoleMappingPermission) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tmRoleMappingPermissionDo) withDO(do gen.Dao) *tmRoleMappingPermissionDo {
	t.DO = *do.(*gen.DO)
	return t
}
