// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/txrps/next-golang-project/model"
)

func newTmSubDistrict(db *gorm.DB, opts ...gen.DOOption) tmSubDistrict {
	_tmSubDistrict := tmSubDistrict{}

	_tmSubDistrict.tmSubDistrictDo.UseDB(db, opts...)
	_tmSubDistrict.tmSubDistrictDo.UseModel(&model.TmSubDistrict{})

	tableName := _tmSubDistrict.tmSubDistrictDo.TableName()
	_tmSubDistrict.ALL = field.NewAsterisk(tableName)
	_tmSubDistrict.SubDistrictID = field.NewInt32(tableName, "sub_district_id")
	_tmSubDistrict.SubDistrictName = field.NewString(tableName, "sub_district_name")
	_tmSubDistrict.DistrictID = field.NewInt32(tableName, "district_id")

	_tmSubDistrict.fillFieldMap()

	return _tmSubDistrict
}

type tmSubDistrict struct {
	tmSubDistrictDo

	ALL             field.Asterisk
	SubDistrictID   field.Int32
	SubDistrictName field.String
	DistrictID      field.Int32

	fieldMap map[string]field.Expr
}

func (t tmSubDistrict) Table(newTableName string) *tmSubDistrict {
	t.tmSubDistrictDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tmSubDistrict) As(alias string) *tmSubDistrict {
	t.tmSubDistrictDo.DO = *(t.tmSubDistrictDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tmSubDistrict) updateTableName(table string) *tmSubDistrict {
	t.ALL = field.NewAsterisk(table)
	t.SubDistrictID = field.NewInt32(table, "sub_district_id")
	t.SubDistrictName = field.NewString(table, "sub_district_name")
	t.DistrictID = field.NewInt32(table, "district_id")

	t.fillFieldMap()

	return t
}

func (t *tmSubDistrict) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tmSubDistrict) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 3)
	t.fieldMap["sub_district_id"] = t.SubDistrictID
	t.fieldMap["sub_district_name"] = t.SubDistrictName
	t.fieldMap["district_id"] = t.DistrictID
}

func (t tmSubDistrict) clone(db *gorm.DB) tmSubDistrict {
	t.tmSubDistrictDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tmSubDistrict) replaceDB(db *gorm.DB) tmSubDistrict {
	t.tmSubDistrictDo.ReplaceDB(db)
	return t
}

type tmSubDistrictDo struct{ gen.DO }

func (t tmSubDistrictDo) Debug() *tmSubDistrictDo {
	return t.withDO(t.DO.Debug())
}

func (t tmSubDistrictDo) WithContext(ctx context.Context) *tmSubDistrictDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tmSubDistrictDo) ReadDB() *tmSubDistrictDo {
	return t.Clauses(dbresolver.Read)
}

func (t tmSubDistrictDo) WriteDB() *tmSubDistrictDo {
	return t.Clauses(dbresolver.Write)
}

func (t tmSubDistrictDo) Session(config *gorm.Session) *tmSubDistrictDo {
	return t.withDO(t.DO.Session(config))
}

func (t tmSubDistrictDo) Clauses(conds ...clause.Expression) *tmSubDistrictDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tmSubDistrictDo) Returning(value interface{}, columns ...string) *tmSubDistrictDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tmSubDistrictDo) Not(conds ...gen.Condition) *tmSubDistrictDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tmSubDistrictDo) Or(conds ...gen.Condition) *tmSubDistrictDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tmSubDistrictDo) Select(conds ...field.Expr) *tmSubDistrictDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tmSubDistrictDo) Where(conds ...gen.Condition) *tmSubDistrictDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tmSubDistrictDo) Order(conds ...field.Expr) *tmSubDistrictDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tmSubDistrictDo) Distinct(cols ...field.Expr) *tmSubDistrictDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tmSubDistrictDo) Omit(cols ...field.Expr) *tmSubDistrictDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tmSubDistrictDo) Join(table schema.Tabler, on ...field.Expr) *tmSubDistrictDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tmSubDistrictDo) LeftJoin(table schema.Tabler, on ...field.Expr) *tmSubDistrictDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tmSubDistrictDo) RightJoin(table schema.Tabler, on ...field.Expr) *tmSubDistrictDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tmSubDistrictDo) Group(cols ...field.Expr) *tmSubDistrictDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tmSubDistrictDo) Having(conds ...gen.Condition) *tmSubDistrictDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tmSubDistrictDo) Limit(limit int) *tmSubDistrictDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tmSubDistrictDo) Offset(offset int) *tmSubDistrictDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tmSubDistrictDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *tmSubDistrictDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tmSubDistrictDo) Unscoped() *tmSubDistrictDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tmSubDistrictDo) Create(values ...*model.TmSubDistrict) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tmSubDistrictDo) CreateInBatches(values []*model.TmSubDistrict, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tmSubDistrictDo) Save(values ...*model.TmSubDistrict) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tmSubDistrictDo) First() (*model.TmSubDistrict, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TmSubDistrict), nil
	}
}

func (t tmSubDistrictDo) Take() (*model.TmSubDistrict, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TmSubDistrict), nil
	}
}

func (t tmSubDistrictDo) Last() (*model.TmSubDistrict, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TmSubDistrict), nil
	}
}

func (t tmSubDistrictDo) Find() ([]*model.TmSubDistrict, error) {
	result, err := t.DO.Find()
	return result.([]*model.TmSubDistrict), err
}

func (t tmSubDistrictDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TmSubDistrict, err error) {
	buf := make([]*model.TmSubDistrict, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tmSubDistrictDo) FindInBatches(result *[]*model.TmSubDistrict, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tmSubDistrictDo) Attrs(attrs ...field.AssignExpr) *tmSubDistrictDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tmSubDistrictDo) Assign(attrs ...field.AssignExpr) *tmSubDistrictDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tmSubDistrictDo) Joins(fields ...field.RelationField) *tmSubDistrictDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tmSubDistrictDo) Preload(fields ...field.RelationField) *tmSubDistrictDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tmSubDistrictDo) FirstOrInit() (*model.TmSubDistrict, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TmSubDistrict), nil
	}
}

func (t tmSubDistrictDo) FirstOrCreate() (*model.TmSubDistrict, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TmSubDistrict), nil
	}
}

func (t tmSubDistrictDo) FindByPage(offset int, limit int) (result []*model.TmSubDistrict, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tmSubDistrictDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tmSubDistrictDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tmSubDistrictDo) Delete(models ...*model.TmSubDistrict) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tmSubDistrictDo) withDO(do gen.Dao) *tmSubDistrictDo {
	t.DO = *do.(*gen.DO)
	return t
}
