// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/txrps/next-golang-project/model"
)

func newTmCountry(db *gorm.DB, opts ...gen.DOOption) tmCountry {
	_tmCountry := tmCountry{}

	_tmCountry.tmCountryDo.UseDB(db, opts...)
	_tmCountry.tmCountryDo.UseModel(&model.TmCountry{})

	tableName := _tmCountry.tmCountryDo.TableName()
	_tmCountry.ALL = field.NewAsterisk(tableName)
	_tmCountry.CountryID = field.NewInt32(tableName, "CountryID")
	_tmCountry.CountryName = field.NewString(tableName, "CountryName")

	_tmCountry.fillFieldMap()

	return _tmCountry
}

type tmCountry struct {
	tmCountryDo

	ALL         field.Asterisk
	CountryID   field.Int32
	CountryName field.String

	fieldMap map[string]field.Expr
}

func (t tmCountry) Table(newTableName string) *tmCountry {
	t.tmCountryDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tmCountry) As(alias string) *tmCountry {
	t.tmCountryDo.DO = *(t.tmCountryDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tmCountry) updateTableName(table string) *tmCountry {
	t.ALL = field.NewAsterisk(table)
	t.CountryID = field.NewInt32(table, "CountryID")
	t.CountryName = field.NewString(table, "CountryName")

	t.fillFieldMap()

	return t
}

func (t *tmCountry) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tmCountry) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 2)
	t.fieldMap["CountryID"] = t.CountryID
	t.fieldMap["CountryName"] = t.CountryName
}

func (t tmCountry) clone(db *gorm.DB) tmCountry {
	t.tmCountryDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tmCountry) replaceDB(db *gorm.DB) tmCountry {
	t.tmCountryDo.ReplaceDB(db)
	return t
}

type tmCountryDo struct{ gen.DO }

func (t tmCountryDo) Debug() *tmCountryDo {
	return t.withDO(t.DO.Debug())
}

func (t tmCountryDo) WithContext(ctx context.Context) *tmCountryDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tmCountryDo) ReadDB() *tmCountryDo {
	return t.Clauses(dbresolver.Read)
}

func (t tmCountryDo) WriteDB() *tmCountryDo {
	return t.Clauses(dbresolver.Write)
}

func (t tmCountryDo) Session(config *gorm.Session) *tmCountryDo {
	return t.withDO(t.DO.Session(config))
}

func (t tmCountryDo) Clauses(conds ...clause.Expression) *tmCountryDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tmCountryDo) Returning(value interface{}, columns ...string) *tmCountryDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tmCountryDo) Not(conds ...gen.Condition) *tmCountryDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tmCountryDo) Or(conds ...gen.Condition) *tmCountryDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tmCountryDo) Select(conds ...field.Expr) *tmCountryDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tmCountryDo) Where(conds ...gen.Condition) *tmCountryDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tmCountryDo) Order(conds ...field.Expr) *tmCountryDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tmCountryDo) Distinct(cols ...field.Expr) *tmCountryDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tmCountryDo) Omit(cols ...field.Expr) *tmCountryDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tmCountryDo) Join(table schema.Tabler, on ...field.Expr) *tmCountryDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tmCountryDo) LeftJoin(table schema.Tabler, on ...field.Expr) *tmCountryDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tmCountryDo) RightJoin(table schema.Tabler, on ...field.Expr) *tmCountryDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tmCountryDo) Group(cols ...field.Expr) *tmCountryDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tmCountryDo) Having(conds ...gen.Condition) *tmCountryDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tmCountryDo) Limit(limit int) *tmCountryDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tmCountryDo) Offset(offset int) *tmCountryDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tmCountryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *tmCountryDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tmCountryDo) Unscoped() *tmCountryDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tmCountryDo) Create(values ...*model.TmCountry) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tmCountryDo) CreateInBatches(values []*model.TmCountry, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tmCountryDo) Save(values ...*model.TmCountry) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tmCountryDo) First() (*model.TmCountry, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TmCountry), nil
	}
}

func (t tmCountryDo) Take() (*model.TmCountry, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TmCountry), nil
	}
}

func (t tmCountryDo) Last() (*model.TmCountry, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TmCountry), nil
	}
}

func (t tmCountryDo) Find() ([]*model.TmCountry, error) {
	result, err := t.DO.Find()
	return result.([]*model.TmCountry), err
}

func (t tmCountryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TmCountry, err error) {
	buf := make([]*model.TmCountry, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tmCountryDo) FindInBatches(result *[]*model.TmCountry, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tmCountryDo) Attrs(attrs ...field.AssignExpr) *tmCountryDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tmCountryDo) Assign(attrs ...field.AssignExpr) *tmCountryDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tmCountryDo) Joins(fields ...field.RelationField) *tmCountryDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tmCountryDo) Preload(fields ...field.RelationField) *tmCountryDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tmCountryDo) FirstOrInit() (*model.TmCountry, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TmCountry), nil
	}
}

func (t tmCountryDo) FirstOrCreate() (*model.TmCountry, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TmCountry), nil
	}
}

func (t tmCountryDo) FindByPage(offset int, limit int) (result []*model.TmCountry, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tmCountryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tmCountryDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tmCountryDo) Delete(models ...*model.TmCountry) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tmCountryDo) withDO(do gen.Dao) *tmCountryDo {
	t.DO = *do.(*gen.DO)
	return t
}
