// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTbGenerateBarcode = "tb_generate_barcode"

// TbGenerateBarcode mapped from table <tb_generate_barcode>
type TbGenerateBarcode struct {
	GenerateID  int32          `gorm:"column:generate_id;primaryKey;autoIncrement:true" json:"generate_id"`
	MailTypeID  int32          `gorm:"column:mail_type_id;not null" json:"mail_type_id"`
	Year        int32          `gorm:"column:year" json:"year"`
	BarcodeFrom string         `gorm:"column:barcode_from;not null" json:"barcode_from"`
	BarcodeTo   string         `gorm:"column:barcode_to;not null" json:"barcode_to"`
	Quality     int64          `gorm:"column:quality;not null" json:"quality"`
	DocTypeID   int32          `gorm:"column:doc_type_id;not null" json:"doc_type_id"`
	CreatedAt   time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	CreatedBy   string         `gorm:"column:created_by;not null" json:"created_by"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	UpdatedBy   string         `gorm:"column:updated_by;not null" json:"updated_by"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	DeletedBy   string         `gorm:"column:deleted_by" json:"deleted_by"`
	IsDelete    bool           `gorm:"column:is_delete" json:"is_delete"`
}

// TableName TbGenerateBarcode's table name
func (*TbGenerateBarcode) TableName() string {
	return TableNameTbGenerateBarcode
}
