// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTbRoute = "tb_route"

// TbRoute mapped from table <tb_route>
type TbRoute struct {
	RouteID       int32          `gorm:"column:route_id;primaryKey;autoIncrement:true" json:"route_id"`
	Road          string         `gorm:"column:road;not null" json:"road"`
	PostcalCode   string         `gorm:"column:postcal_code;not null" json:"postcal_code"`
	CountryID     int32          `gorm:"column:country_id;not null" json:"country_id"`
	ProvinceID    int32          `gorm:"column:province_id;not null" json:"province_id"`
	DistrictID    int32          `gorm:"column:district_id;not null" json:"district_id"`
	SubDistrictID int32          `gorm:"column:sub_district_id;not null" json:"sub_district_id"`
	CreatedAt     time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	CreatedBy     string         `gorm:"column:created_by;not null" json:"created_by"`
	UpdatedAt     time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	UpdatedBy     string         `gorm:"column:updated_by;not null" json:"updated_by"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	DeletedBy     string         `gorm:"column:deleted_by" json:"deleted_by"`
	IsDelete      bool           `gorm:"column:is_delete" json:"is_delete"`
}

// TableName TbRoute's table name
func (*TbRoute) TableName() string {
	return TableNameTbRoute
}
