// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTbGenerateBarcode = "TbGenerateBarcode"

// TbGenerateBarcode mapped from table <TbGenerateBarcode>
type TbGenerateBarcode struct {
	GenerateID  int32     `gorm:"column:GenerateID;primaryKey;autoIncrement:true" json:"GenerateID"`
	MailTypeID  int32     `gorm:"column:MailTypeID;not null" json:"MailTypeID"`
	Year        int32     `gorm:"column:Year" json:"Year"`
	BarcodeFrom string    `gorm:"column:BarcodeFrom;not null" json:"BarcodeFrom"`
	BarcodeTo   string    `gorm:"column:BarcodeTo;not null" json:"BarcodeTo"`
	Quality     int64     `gorm:"column:Quality;not null" json:"Quality"`
	DocTypeID   int32     `gorm:"column:DocTypeID;not null" json:"DocTypeID"`
	Created     time.Time `gorm:"column:Created;not null;default:CURRENT_TIMESTAMP" json:"Created"`
	CreateBy    string    `gorm:"column:CreateBy;not null" json:"CreateBy"`
	Updated     time.Time `gorm:"column:Updated;not null;default:CURRENT_TIMESTAMP" json:"Updated"`
	UpdateBy    string    `gorm:"column:UpdateBy;not null" json:"UpdateBy"`
	Deleted     time.Time `gorm:"column:Deleted" json:"Deleted"`
	DeleteBy    string    `gorm:"column:DeleteBy" json:"DeleteBy"`
	IsDelete    bool      `gorm:"column:IsDelete" json:"IsDelete"`
}

// TableName TbGenerateBarcode's table name
func (*TbGenerateBarcode) TableName() string {
	return TableNameTbGenerateBarcode
}
