// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTbRoute = "TbRoute"

// TbRoute mapped from table <TbRoute>
type TbRoute struct {
	RouteID       int32     `gorm:"column:RouteID;primaryKey;autoIncrement:true" json:"RouteID"`
	Road          string    `gorm:"column:Road;not null" json:"Road"`
	PostcalCode   string    `gorm:"column:PostcalCode;not null" json:"PostcalCode"`
	CountryID     int32     `gorm:"column:CountryID;not null" json:"CountryID"`
	ProvinceID    int32     `gorm:"column:ProvinceID;not null" json:"ProvinceID"`
	DistrictID    int32     `gorm:"column:DistrictID;not null" json:"DistrictID"`
	SubdistrictID int32     `gorm:"column:SubdistrictID;not null" json:"SubdistrictID"`
	Created       time.Time `gorm:"column:Created;not null;default:CURRENT_TIMESTAMP" json:"Created"`
	CreateBy      string    `gorm:"column:CreateBy;not null" json:"CreateBy"`
	Updated       time.Time `gorm:"column:Updated;not null;default:CURRENT_TIMESTAMP" json:"Updated"`
	UpdateBy      string    `gorm:"column:UpdateBy;not null" json:"UpdateBy"`
	Deleted       time.Time `gorm:"column:Deleted" json:"Deleted"`
	DeleteBy      string    `gorm:"column:DeleteBy" json:"DeleteBy"`
	IsDelete      bool      `gorm:"column:IsDelete" json:"IsDelete"`
}

// TableName TbRoute's table name
func (*TbRoute) TableName() string {
	return TableNameTbRoute
}
