// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTmCountry = "tm_country"

// TmCountry mapped from table <tm_country>
type TmCountry struct {
	CountryID   int32  `gorm:"column:country_id;primaryKey;autoIncrement:true" json:"country_id"`
	CountryName string `gorm:"column:country_name;not null" json:"country_name"`
}

// TableName TmCountry's table name
func (*TmCountry) TableName() string {
	return TableNameTmCountry
}
