// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTmDistrict = "tm_district"

// TmDistrict mapped from table <tm_district>
type TmDistrict struct {
	DistrictID   int32  `gorm:"column:district_id;primaryKey;autoIncrement:true" json:"district_id"`
	DistrictName string `gorm:"column:district_name;not null" json:"district_name"`
	ProvinceID   int32  `gorm:"column:province_id;not null" json:"province_id"`
}

// TableName TmDistrict's table name
func (*TmDistrict) TableName() string {
	return TableNameTmDistrict
}
