// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTmMenu = "tm_menu"

// TmMenu mapped from table <tm_menu>
type TmMenu struct {
	MenuID           int32   `gorm:"column:menu_id;primaryKey" json:"menu_id"`
	ParentID         int32   `gorm:"column:parent_id" json:"parent_id"`
	MenuName         string  `gorm:"column:menu_name;not null" json:"menu_name"`
	MenuType         int32   `gorm:"column:menu_type;not null" json:"menu_type"`
	Level            int32   `gorm:"column:level;not null" json:"level"`
	Route            string  `gorm:"column:route;not null" json:"route"`
	Icon             string  `gorm:"column:icon" json:"icon"`
	IsDisplay        bool    `gorm:"column:is_display;not null" json:"is_display"`
	IsSetPermission  bool    `gorm:"column:is_set_permission;not null" json:"is_set_permission"`
	IsDisable        bool    `gorm:"column:is_disable;not null" json:"is_disable"`
	IsView           bool    `gorm:"column:is_view;not null" json:"is_view"`
	IsManage         bool    `gorm:"column:is_manage;not null" json:"is_manage"`
	IsShowbreadcrumb bool    `gorm:"column:is_showbreadcrumb;not null" json:"is_showbreadcrumb"`
	IsActive         bool    `gorm:"column:is_active;not null" json:"is_active"`
	Order_           float64 `gorm:"column:order;not null" json:"order"`
}

// TableName TmMenu's table name
func (*TmMenu) TableName() string {
	return TableNameTmMenu
}
