// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTmMasterDatum = "tm_master_data"

// TmMasterDatum mapped from table <tm_master_data>
type TmMasterDatum struct {
	MasterDataID     int32  `gorm:"column:master_data_id;primaryKey" json:"master_data_id"`
	MasterDataName   string `gorm:"column:master_data_name;not null" json:"master_data_name"`
	IsActive         bool   `gorm:"column:is_active;default:true" json:"is_active"`
	MasterDataTypeID int32  `gorm:"column:master_data_type_id;not null" json:"master_data_type_id"`
	Code             string `gorm:"column:code" json:"code"`
}

// TableName TmMasterDatum's table name
func (*TmMasterDatum) TableName() string {
	return TableNameTmMasterDatum
}
