// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTmMasterDataType = "tm_master_data_type"

// TmMasterDataType mapped from table <tm_master_data_type>
type TmMasterDataType struct {
	MasterDataTypeID   int32  `gorm:"column:master_data_type_id;primaryKey" json:"master_data_type_id"`
	MasterDataTypeName string `gorm:"column:master_data_type_name;not null" json:"master_data_type_name"`
}

// TableName TmMasterDataType's table name
func (*TmMasterDataType) TableName() string {
	return TableNameTmMasterDataType
}
