// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTmProvince = "tm_province"

// TmProvince mapped from table <tm_province>
type TmProvince struct {
	ProvinceID   int32  `gorm:"column:province_id;primaryKey;autoIncrement:true" json:"province_id"`
	ProvinceName string `gorm:"column:province_name;not null" json:"province_name"`
	CountryID    int32  `gorm:"column:country_id;not null" json:"country_id"`
}

// TableName TmProvince's table name
func (*TmProvince) TableName() string {
	return TableNameTmProvince
}
