// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTmRoleMappingPermission = "tm_role_mapping_permission"

// TmRoleMappingPermission mapped from table <tm_role_mapping_permission>
type TmRoleMappingPermission struct {
	RoleID     int32 `gorm:"column:role_id;primaryKey" json:"role_id"`
	MenuID     int32 `gorm:"column:menu_id;primaryKey" json:"menu_id"`
	Permission int32 `gorm:"column:permission;not null;default:1" json:"permission"`
}

// TableName TmRoleMappingPermission's table name
func (*TmRoleMappingPermission) TableName() string {
	return TableNameTmRoleMappingPermission
}
