// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTmRole = "tm_role"

// TmRole mapped from table <tm_role>
type TmRole struct {
	RoleID   int32  `gorm:"column:role_id;primaryKey;autoIncrement:true" json:"role_id"`
	RoleName string `gorm:"column:role_name;not null" json:"role_name"`
	IsActive bool   `gorm:"column:is_active;not null" json:"is_active"`
}

// TableName TmRole's table name
func (*TmRole) TableName() string {
	return TableNameTmRole
}
