// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTmSubDistrict = "tm_sub_district"

// TmSubDistrict mapped from table <tm_sub_district>
type TmSubDistrict struct {
	SubDistrictID   int32  `gorm:"column:sub_district_id;primaryKey;autoIncrement:true" json:"sub_district_id"`
	SubDistrictName string `gorm:"column:sub_district_name;not null" json:"sub_district_name"`
	DistrictID      int32  `gorm:"column:district_id;not null" json:"district_id"`
}

// TableName TmSubDistrict's table name
func (*TmSubDistrict) TableName() string {
	return TableNameTmSubDistrict
}
