// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTmCountry = "TmCountry"

// TmCountry mapped from table <TmCountry>
type TmCountry struct {
	CountryID   int32  `gorm:"column:CountryID;primaryKey;autoIncrement:true" json:"CountryID"`
	CountryName string `gorm:"column:CountryName;not null" json:"CountryName"`
}

// TableName TmCountry's table name
func (*TmCountry) TableName() string {
	return TableNameTmCountry
}
