// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTmDistrict = "TmDistrict"

// TmDistrict mapped from table <TmDistrict>
type TmDistrict struct {
	DistrictID   int32  `gorm:"column:DistrictID;primaryKey;autoIncrement:true" json:"DistrictID"`
	DistrictName string `gorm:"column:DistrictName;not null" json:"DistrictName"`
	ProvinceID   int32  `gorm:"column:ProvinceID;not null" json:"ProvinceID"`
}

// TableName TmDistrict's table name
func (*TmDistrict) TableName() string {
	return TableNameTmDistrict
}
