// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTmMasterDatum = "TmMasterData"

// TmMasterDatum mapped from table <TmMasterData>
type TmMasterDatum struct {
	MasterDataID     int32  `gorm:"column:MasterDataID;primaryKey" json:"MasterDataID"`
	MasterDataName   string `gorm:"column:MasterDataName;not null" json:"MasterDataName"`
	IsActive         bool   `gorm:"column:IsActive;default:true" json:"IsActive"`
	MasterDataTypeID int32  `gorm:"column:MasterDataTypeID;not null" json:"MasterDataTypeID"`
	Code             string `gorm:"column:Code" json:"Code"`
}

// TableName TmMasterDatum's table name
func (*TmMasterDatum) TableName() string {
	return TableNameTmMasterDatum
}
