// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTmMasterDataType = "TmMasterDataType"

// TmMasterDataType mapped from table <TmMasterDataType>
type TmMasterDataType struct {
	MasterDataTypeID   int32  `gorm:"column:MasterDataTypeID;primaryKey" json:"MasterDataTypeID"`
	MasterDataTypeName string `gorm:"column:MasterDataTypeName;not null" json:"MasterDataTypeName"`
}

// TableName TmMasterDataType's table name
func (*TmMasterDataType) TableName() string {
	return TableNameTmMasterDataType
}
