// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTmMenu = "TmMenu"

// TmMenu mapped from table <TmMenu>
type TmMenu struct {
	MenuID           int32   `gorm:"column:MenuID;primaryKey" json:"MenuID"`
	ParentID         int32   `gorm:"column:ParentID" json:"ParentID"`
	MenuName         string  `gorm:"column:MenuName;not null" json:"MenuName"`
	MenuType         int32   `gorm:"column:MenuType;not null" json:"MenuType"`
	Level            int32   `gorm:"column:Level;not null" json:"Level"`
	Route            string  `gorm:"column:Route;not null" json:"Route"`
	Icon             string  `gorm:"column:Icon" json:"Icon"`
	IsDisplay        bool    `gorm:"column:IsDisplay;not null" json:"IsDisplay"`
	IsSetPermission  bool    `gorm:"column:IsSetPermission;not null" json:"IsSetPermission"`
	IsDisable        bool    `gorm:"column:IsDisable;not null" json:"IsDisable"`
	IsView           bool    `gorm:"column:IsView;not null" json:"IsView"`
	IsManage         bool    `gorm:"column:IsManage;not null" json:"IsManage"`
	IsShowbreadcrumb bool    `gorm:"column:IsShowbreadcrumb;not null" json:"IsShowbreadcrumb"`
	IsActive         bool    `gorm:"column:IsActive;not null" json:"IsActive"`
	Order_           float64 `gorm:"column:Order;not null" json:"Order"`
}

// TableName TmMenu's table name
func (*TmMenu) TableName() string {
	return TableNameTmMenu
}
