// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTmProvince = "TmProvince"

// TmProvince mapped from table <TmProvince>
type TmProvince struct {
	ProvinceID   int32  `gorm:"column:ProvinceID;primaryKey;autoIncrement:true" json:"ProvinceID"`
	ProvinceName string `gorm:"column:ProvinceName;not null" json:"ProvinceName"`
	CountryID    int32  `gorm:"column:CountryID;not null" json:"CountryID"`
}

// TableName TmProvince's table name
func (*TmProvince) TableName() string {
	return TableNameTmProvince
}
