// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTmRole = "TmRole"

// TmRole mapped from table <TmRole>
type TmRole struct {
	RoleID   int32  `gorm:"column:RoleID;primaryKey;autoIncrement:true" json:"RoleID"`
	RoleName string `gorm:"column:RoleName;not null" json:"RoleName"`
	IsActive bool   `gorm:"column:IsActive;not null" json:"IsActive"`
}

// TableName TmRole's table name
func (*TmRole) TableName() string {
	return TableNameTmRole
}
