// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTmRoleMappingPermission = "TmRoleMappingPermission"

// TmRoleMappingPermission mapped from table <TmRoleMappingPermission>
type TmRoleMappingPermission struct {
	RoleID     int32 `gorm:"column:RoleID;primaryKey" json:"RoleID"`
	MenuID     int32 `gorm:"column:MenuID;primaryKey" json:"MenuID"`
	Permission int32 `gorm:"column:Permission;not null;default:1" json:"Permission"`
}

// TableName TmRoleMappingPermission's table name
func (*TmRoleMappingPermission) TableName() string {
	return TableNameTmRoleMappingPermission
}
